/**
 * Created by mosesesan on 30/08/2017.
 */

export const REGISTERING = 'REGISTERING';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const LOGGING_IN = 'LOGGING_IN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';

export const SMS_VERIFICATION_SENT = 'SMS_VERIFICATION_SENT';
export const SMS_VERIFICATION_FAILED = 'SMS_VERIFICATION_FAILED';
export const EMAIL_VERIFICATION_SENT = 'EMAIL_VERIFICATION_SENT';
export const EMAIL_VERIFICATION_FAILED = 'EMAIL_VERIFICATION_FAILED';

export const CODE_VERIFICATION_SUCCESS = 'CODE_VERIFICATION_SUCCESS';
export const CODE_VERIFICATION_FAILED = 'CODE_VERIFICATION_FAILED';

export const PASSWORD_REMINDER_SENT = 'PASSWORD_REMINDER_SENT';
export const PASSWORD_REMINDER_FAILED = 'PASSWORD_REMINDER_FAILED';